# Instrument
symbol: "BTCUSDT-PERP"
venue: "BINANCE"
instrument_id: "BTCUSDT-PERP.BINANCE"
bar_type: "BTCUSDT-PERP.BINANCE-5-MINUTE-LAST-EXTERNAL"

# Backtest-Zeitraum
start_date: "2024-10-01T00:00:00Z"
end_date: "2024-10-31T00:00:00Z"

# Strategie-Parameter
fast_ema_period: [5, 10, 15]
slow_ema_period: [20, 30]
twap_horizon_secs: [25, 30]
twap_interval_secs: [2, 5]

# Risk-Parameter
trade_size: [0.5]
close_positions_on_stop: [true]
risk_percent: 0.01
max_leverage: 2
min_account_balance: 1000

# Account/Venue-Parameter
starting_account_balance: "100000 USDT"
base_currency: "USDT"
account_type: "MARGIN"
oms_type: "NETTING"